model:
  weight_decay: 0.0001
  batch_size: 64
  beta_1: 0.9
  beta_2: 0.999
  lr: 1.0e-3
  init_width: 28
  init_length: 28
  resnet_config:
    first_conv:
      in_channels: 1
      out_channels: 32
      kernel_size: 3
      stride: 2
      padding: 1
    block_list: [
      {
        in_channels: 32,
        out_channels: 16,
        kernel_size: 3,
        stride: 2,
        padding: 1,
      },
      {
        in_channels: 16,
        out_channels: 8,
        kernel_size: 3,
        stride: 1,
        padding: 'same',
      },
    ]
    pool_size: 2
  mlp_config:
    block_list: [
      {
        in_size: 72,
        out_size: 64,
        activation_fun: "relu",
        batch_norm: True,
        dropout: 0.1
      },
      {
        in_size: 64,
        out_size: 10,
        activation_fun: "logsoftmax",
        batch_norm: False,
        dropout: 0.0
      },
    ]
  img_key: 0
  class_key: 1